import { Component } from "@angular/core";

@Component({
    selector: "Agreement",
    templateUrl: "./agreement.component.html"
})
export class AgreementComponent {
    private legal: string = `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam posuere, dolor sit amet sodales egestas, ante felis pulvinar nunc, id scelerisque lectus enim a odio. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aenean id diam mollis, tempor risus at, mattis neque. Donec in dignissim erat. Etiam tincidunt blandit ex non sagittis. Donec cursus nisl lacinia odio volutpat accumsan. Duis commodo quam sit amet enim aliquet, sed blandit neque sollicitudin. Fusce mollis, purus ac sagittis fermentum, turpis nisi facilisis lorem, eu fermentum ipsum purus condimentum orci. Etiam fermentum dolor iaculis, gravida libero in, condimentum felis. In vel faucibus nunc. Nam interdum in nibh vitae aliquam. Quisque eu interdum est. Aenean at laoreet velit. Donec hendrerit dolor in sodales venenatis. In ac sem tristique, porta erat sed, sodales massa. Mauris tincidunt ante ut elit posuere viverra quis ac dolor.

    Etiam dapibus enim elit, a iaculis turpis maximus quis. Maecenas sit amet mi feugiat, hendrerit metus at, cursus est. Donec a turpis libero. Mauris tortor nisl, elementum quis tortor sit amet, posuere gravida sem. Etiam posuere vestibulum orci, in blandit ex cursus non. Curabitur pretium iaculis dignissim. Fusce nec consectetur lorem. Ut bibendum lacinia sapien, maximus suscipit odio posuere vel. Etiam ultrices nibh et lorem pellentesque, sed fermentum erat condimentum. Phasellus interdum interdum nisi at luctus.
    
    Aliquam consectetur mollis lacus, id porttitor lectus pulvinar sit amet. Vestibulum congue rutrum finibus. Nam placerat nibh et quam mollis dapibus. Nulla aliquam efficitur libero in tristique. Duis ac turpis id turpis suscipit laoreet. Fusce semper auctor purus non luctus. Nullam eleifend, neque et interdum pharetra, quam purus eleifend mi, eget scelerisque magna tellus eu urna. Vestibulum venenatis bibendum eros, vitae vulputate elit consectetur nec. Sed vulputate id odio id pretium. Etiam ornare, sapien nec mollis lacinia, magna tortor aliquet eros, nec luctus ligula justo eu mi. Vivamus vitae sodales metus, et condimentum lorem. Suspendisse nec cursus lectus.
    
    Maecenas ligula mauris, varius sit amet pharetra quis, rhoncus sed augue. In hendrerit ut quam ac ullamcorper. Curabitur ex ipsum, malesuada et nisi nec, porta egestas justo. Ut fermentum est orci, efficitur vehicula ante rhoncus in. Suspendisse venenatis, nisi ac pulvinar porttitor, odio purus consectetur urna, eu eleifend nibh nisl vel nisi. Sed nisi mauris, malesuada vel odio non, lacinia convallis augue. Ut elementum et ex sed porttitor. Maecenas varius a nulla sed venenatis. Donec finibus aliquam nibh, ut fringilla felis sagittis et. Vestibulum blandit justo vitae gravida finibus. Etiam dolor lacus, luctus sed nisl non, cursus sagittis sem. Ut luctus cursus magna quis consequat.
    
    Suspendisse erat erat, aliquam molestie lorem a, malesuada ornare nulla. Curabitur molestie ultrices lorem eu commodo. Nulla eget diam ac tellus interdum hendrerit. Pellentesque sit amet orci risus. Integer sed eros vehicula, condimentum velit eget, semper diam. Proin tempus eget magna eget facilisis. Quisque ornare convallis diam, quis tempus neque lacinia ut. Donec sit amet augue vel felis malesuada sagittis. Sed nec congue elit. Praesent ac tristique risus. Integer rhoncus ullamcorper elit, nec facilisis ante suscipit vel. Morbi eu feugiat sem. Fusce sed laoreet mi. Sed gravida neque et nunc semper dapibus.`;
}
