# Generated by Django 2.2.6 on 2019-10-23 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlternativeUser',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.PositiveIntegerField()),
                ('savings', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('created', 1), ('approved_by_payer', 2), ('denied_by_payer', 3), ('approved_by_bank', 4), ('denied_by_bank', 5)], max_length=255)),
                ('payee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_payee', to='moneyengine.AlternativeUser')),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_payer', to='moneyengine.AlternativeUser')),
            ],
        ),
    ]
