# Generated by Django 2.2.6 on 2019-11-10 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneyengine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionstatuschange',
            name='new_status',
            field=models.CharField(choices=[('created', 'created'), ('approved_by_payer', 'approved_by_payer'), ('denied_by_payer', 'denied_by_payer'), ('approved_by_bank', 'approved_by_bank'), ('denied_by_bank', 'denied_by_bank')], max_length=255),
        ),
    ]
