# Generated by Django 2.2.6 on 2019-11-05 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Iban',
            fields=[
                ('iban_id', models.AutoField(primary_key=True, serialize=False)),
                ('account_owner', models.CharField(max_length=255)),
                ('alias', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=2)),
                ('check_digit', models.CharField(max_length=2)),
                ('bank', models.IntegerField()),
                ('number', models.CharField(max_length=30)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('savings', models.DecimalField(decimal_places=2, max_digits=14)),
                ('destination_iban', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_payeeiban', to='moneyengine.Iban')),
                ('source_iban', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_payeriban', to='moneyengine.Iban')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionStatusChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_status', models.CharField(choices=[('created', 1), ('approved_by_payer', 2), ('denied_by_payer', 3), ('approved_by_bank', 4), ('denied_by_bank', 5)], max_length=255)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('subject_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactionstatuschange_subjecttransaction', to='moneyengine.Transaction')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=255)),
                ('iban', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moneyengine.Iban')),
            ],
        ),
    ]
